on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - run: make init
      - run: make lint
      - run: make test
